# v0.030_000
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
clone_depth: 1
clone_folder: C:\projects\alien-pcre2

#environment:
#    matrix:
# DEV NOTE, CORRELATION #ap011: hackish code, setting ALIEN_INSTALL_TYPE=share causes Alien::gmake to fail to properly install in system mode with pre-installed C:\strawberry\c\bin\gmake.exe
        # share test, compile PCRE2 from source
#        - ALIEN_INSTALL_TYPE: share

# NEED FIX, CORRELATION #ap010: chocolatey does not support installation of libpcre2*
       # system test, uses PCRE2 from chocolatey
#        - ALIEN_INSTALL_TYPE: system

# DEV NOTE, CORRELATION #ap001: must install IO::Socket::SSL & Alien::Build from Makefile.PL (which becomes META.json, for CPAN) & .travis.yml & appveyor.yml 
# DEV NOTE: do not test IO::Socket::SSL, about 50% of the time it hangs on the test after "t/sysread_write.t ................. ok"
# DEV NOTE, CORRELATION #ap003: must set env var MAKE=gmake to change Alien::Build process, does not work to set it in Makefile.PL
# DEV NOTE, CORRELATION #ap004: must set env var PATH with C:\Progra~1\ instead of C:\Program Files\ to avoid error "file not found C:\Program" in Alien::Build process
install:
- cmd: >-

    choco install curl

    curl -V

    curl -o perl.msi http://strawberryperl.com/download/5.26.0.1/strawberry-perl-5.26.0.1-32bit.msi

    msiexec /i perl.msi /quiet /qn /norestart

    set PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\windows\system32;C:\windows;%path%

    gcc -v

    g++ -v

    perl -V

    perl -e"require CPAN;CPAN::Shell->verbose('install','App::cpanminus');"

    cpanm --verbose --notest IO::Socket::SSL

    perl Makefile.PL

    cpanm --verbose --installdeps .

    set PERL5LIB=blib;lib

    set

    perl -le "print for @INC"

    gmake test

    gmake install

    perl -le "use Alien::PCRE2; use Env qw(@PATH); unshift @PATH, Alien::PCRE2->bin_dir(); print `sh pcre2-config --version`, \"\n\"; print `sh pcre2-config --cflags`, \"\n\";"

build: off
test: off
deploy: off
